CollegeSystemSystem/Models/Student.cs
using System.ComponentModel.DataAnnotations;

namespace CollegeSystemSystem.Models
{
    public class Student
    {
        [Display(Name = "Student ID")]

        public int Id { get; set; }
        [Display(Name = "Student Name")]
        [Required(ErrorMessage = "{0} is required.")]
        [StringLength(60, MinimumLength = 3, ErrorMessage = "{0} size should be between {2} and {1}.")]

        public string Name { get; set; }

        [Required(ErrorMessage = "{0} required.")]
        [Display(Name = "Birth Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime BirthDate { get; set; }
        public Course? Course { get; set; }
        public int CourseId { get; set; }
        public IEnumerable<Grade> Grades { get; set; } = new List<Grade>();

        public Student()
        {

        }

        public Student(int id, string name, DateTime birthDate, Course course)
        {
            Id = id;
            Name = name;
            BirthDate = birthDate;
            Course = course;
        }
    }
}

CollegeSystemSystem/Controllers/GradesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CollegeSystemSystem.Data;
using CollegeSystemSystem.Models;
using CollegeSystemSystem.Services;

namespace CollegeSystemSystem.Controllers
{
    public class GradesController : Controller
    {
        private readonly CollegeSystemDbContext _context;
        private readonly StudentService _studentService;
        private readonly SubjectService _subjectService;
        private readonly TeacherService _teacherService;

        public GradesController(CollegeSystemDbContext context, StudentService studentService, SubjectService subjectService, TeacherService teacherService)
        {
            _context = context;
            _studentService = studentService;
            _subjectService = subjectService;
            _teacherService = teacherService;
        }

        // GET: Grades
        public async Task<IActionResult> Index()
        {
            var collegeSystemDbContext = _context.Grade.Include(g => g.Student).Include(g => g.Subject);
            return View(await collegeSystemDbContext.ToListAsync());
        }

        // GET: Grades/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grade = await _context.Grade
                .Include(g => g.Student)
                .Include(g => g.Subject)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (grade == null)
            {
                return NotFound();
            }

            return View(grade);
        }

        // GET: Grades/Create
        public IActionResult Create()
        {
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "Id");
            ViewData["SubjectId"] = new SelectList(_context.Subject, "Id", "Id");
            return View();
        }

        // POST: Grades/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,GradeNumber,StudentId,SubjectId")] Grade grade)
        {
            grade.Student = await _studentService.FindByIdAsync(grade.StudentId);
            List<Subject> subjects = await _subjectService.FindByCourseIdAsync(grade.Student.CourseId);



            foreach (Subject subject in subjects)
            {
                grade.Id = 0;
                grade.SubjectId = subject.Id;
                grade.Subject = await _subjectService.FindByIdAsync(grade.SubjectId);
                grade.Subject.Teacher = await _teacherService.FindByIdAsync(grade.Subject.TeacherId);
                ModelState.Clear();
                TryValidateModel(grade);

                if (!ModelState.IsValid)
                {
                    ViewData["StudentId"] = new SelectList(_context.Student, "Id", "Id", grade.StudentId);
                    ViewData["SubjectId"] = new SelectList(_context.Subject, "Id", "Id", grade.SubjectId);
                    return View(grade);

                }

                _context.Add(grade);
                await _context.SaveChangesAsync();
            }


            return RedirectToAction(nameof(Index));

        }

        // GET: Grades/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grade = await _context.Grade
                .Include(s => s.Student)
                .Include(s => s.Subject)
                .Where(s => s.Id == id)
                .FirstOrDefaultAsync();
            
            if (grade == null)
            {
                return NotFound();
            }

            return View(grade);
        }

        // POST: Grades/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,GradeNumber,StudentId,SubjectId")] Grade grade)
        {
            if (id != grade.Id)
            {
                return NotFound();
            }

            grade.Student = await _studentService.FindByIdAsync(grade.StudentId);
            grade.Subject = await _subjectService.FindByIdAsync(grade.SubjectId);
            grade.Subject.Teacher = await _teacherService.FindByIdAsync(grade.Subject.TeacherId);

            grade.StudentId = grade.Student.Id;
            grade.SubjectId = grade.Subject.Id;

            ModelState.Clear();
            TryValidateModel(grade);

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(grade);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GradeExists(grade.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Students", new { id = grade.Student.Id });
            }
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "Id", grade.StudentId);
            ViewData["SubjectId"] = new SelectList(_context.Subject, "Id", "Id", grade.SubjectId);
            return RedirectToAction("Details", "Students", new { id = grade.Student.Id });
        }

        // GET: Grades/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grade = await _context.Grade
                .Include(g => g.Student)
                .Include(g => g.Subject)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (grade == null)
            {
                return NotFound();
            }

            return View(grade);
        }

        // POST: Grades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var grade = await _context.Grade.FindAsync(id);
            _context.Grade.Remove(grade);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GradeExists(int id)
        {
            return _context.Grade.Any(e => e.Id == id);
        }
    }
}

CollegeSystemSystem/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CollegeSystemSystem.Data;
using CollegeSystemSystem.Models;
using CollegeSystemSystem.Services;
using CollegeSystemSystem.Models.ViewModels;
using System.Diagnostics;

namespace CollegeSystemSystem.Controllers
{
    public class StudentsController : Controller
    {
        private readonly CollegeSystemDbContext _context;
        private readonly CourseService _courseService;
        private readonly StudentService _studentService;
        private readonly GradeService _gradeService;

        public StudentsController(CollegeSystemDbContext context, CourseService courseService, StudentService studentService, GradeService gradeService)
        {
            _context = context;
            _courseService = courseService;
            _studentService = studentService;
            _gradeService = gradeService;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            var students = await _studentService.FindAllAsync();

            students.ForEach(student => student.Course = _courseService.FindById(student.CourseId));
            return View(students);
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Student student = await _context.Student
                .Include(c => c.Course)
                .Include(g => g.Grades)
                .ThenInclude(s => s.Subject)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public async Task<IActionResult> Create()
        {
            var courses = await _courseService.FindAllAsync();
            var viewModel = new StudentFormViewModel { Courses = courses };
            return View(viewModel);
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BirthDate,Id,Name,CourseId")] Student student)
        {
            student.Course = await _courseService.FindByIdAsync(student.CourseId);
                        
            ModelState.Clear();
            TryValidateModel(student);

            if (!ModelState.IsValid)
            {
                return View(nameof(Index));
            }

            _context.Add(student);
            await _context.SaveChangesAsync();

            // Bind the Student with subjects and grades (empty at beginning)
            await _gradeService.InsertGradeByCourse(student);

            return RedirectToAction(nameof(Index));
            
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student.FindAsync(id);
            student.Course = await _courseService.FindByIdAsync(student.CourseId);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BirthDate,Id,Name,CourseId")] Student student)
        {
            if (id != student.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try { 
            var student = await _context.Student.FindAsync(id);
            _context.Student.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
            }

            catch (DbUpdateException e)
            {
                return RedirectToAction(nameof(Error), new { message = "The student is binded to the courses and grade, please delete them first." });
            }
        }

        public IActionResult Error(string message)
        {
            var viewModel = new ErrorViewModel
            {
                Message = message,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier

            };

            return View(viewModel);
        }
        private bool StudentExists(int id)
        {
            return _context.Student.Any(e => e.Id == id);
        }
    }
}

CollegeSystemSystem/Views/Students/Create.cshtml
@model CollegeSystemSystem.Models.ViewModels.StudentFormViewModel

@{
    ViewData["Title"] = "Create Student";
}

<h1>Create Student</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Student.BirthDate" class="control-label"></label>
                <input asp-for="Student.BirthDate" class="form-control" />
                <span asp-validation-for="Student.BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.Name" class="control-label"></label>
                <input asp-for="Student.Name" class="form-control" />
                <span asp-validation-for="Student.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.Course" class="control-label"></label>
                <select asp-for="Student.CourseId" asp-items="@(new SelectList(Model.Courses,"Id","CourseName"))" class="form-control"></select>
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
                <a asp-action="Index" class="btn btn-default">Back to List</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

CollegeSystemSystem/Views/Students/Delete.cshtml
@model CollegeSystemSystem.Models.Student

@{
    ViewData["Title"] = "Delete";
}

<h1>Are you sure you want to delete this?</h1>


<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Index" class="btn btn-default">Back to List</a>
    </form>
</div>

CollegeSystemSystem/Views/Students/Details.cshtml
@model CollegeSystemSystem.Models.Student

@{
    ViewData["Title"] = "Details";
}

<h1>Student Details</h1>

<div>
    
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course.CourseName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.CourseName)
        </dd>
    </dl>
</div>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                Subjects Name
            </th>
            <th>
                Grade
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (Grade grade in Model.Grades)
        {
            <tr>

                <td>
                    @grade.Subject.SubjectName
                </td>

                <td>
                    @{
                        if (@grade.GradeNumber == null)
                        {
                            @Html.ActionLink("Add","Edit","Grades", new{id = @grade.Id})
                        }
                        else
                        {
                            @Html.ActionLink(@grade.GradeNumber.ToString(),"Edit","Grades", new{id = @grade.Id})
                        }
                    }

                </td>

            </tr>

        }
    </tbody>
</table>

<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-default">Edit</a> 
    <a asp-action="Index" class="btn btn-default">Back to List</a>
</div>

CollegeSystemSystem/Views/Students/Edit.cshtml
@model CollegeSystemSystem.Models.Student

@{
    ViewData["Title"] = "Edit Student";
}

<h1>Edit Student</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="CourseId" />
            <div class="form-group">
                <label asp-for="Course.CourseName" class="control-label"></label>
                <input asp-for="Course.CourseName" class="form-control" disabled/>
                <span asp-validation-for="Course.CourseName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
                <a class="btn btn-default" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

<div>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

CollegeSystemSystem/Views/Students/Index.cshtml
@model IEnumerable<CollegeSystemSystem.Models.Student>

@{
    ViewData["Title"] = "Student";
}

<h1>Student</h1>

<p>
    <a asp-action="Create" class="btn btn-default">Create New</a>
</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BirthDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">
                        @Html.DisplayFor(modelItem => item.Name)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course.CourseName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BirthDate)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>